version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.0
    steps:
      - checkout
      - run: npm install dredd@13.1.2 --no-optional --global
      - run: dredd demoapihasibul https://qa-customers.cubi.casa/api